Repository chrispinkney/cinesync, pull requests merged in 2023-11, with the labels that each got.

#90 Issue-3: Implement user profile page
  api/src/users/users.service.ts
  web/src/app/dashboard/layout.tsx
  web/src/app/dashboard/userprofile/page.tsx
  web/src/components/Header/AvatarLogo.tsx
  web/src/components/Header/Header.tsx
  web/src/components/UserProfile/DeleteUserProfile.tsx
  web/src/components/UserProfile/ProfileBottom.tsx
  web/src/components/UserProfile/ProfileTop.tsx
  web/src/components/UserProfile/UploadAvatarImage.tsx
  web/src/components/UserProfile/UserProfileMain.tsx
  web/src/context/user.context.tsx
  web/src/utils/cinesync-api/fetch-user.ts
Labels: enhancement, frontend, hacktoberfest-accepted

#117 Issue-104: Map each schema property suchthat it's camel case
  api/prisma/schema.prisma
  api/src/lists/daos/list.dao.ts
  api/src/lists/dtos/create-list-return.dto.ts
  api/src/lists/dtos/create-list.dto.ts
  api/src/lists/dtos/list.dto.ts
  api/src/lists/dtos/movie.dto.ts
  api/src/lists/dtos/update-list-privacy.dto.ts
  api/src/lists/dtos/update-list.dto.ts
  api/src/lists/guards/list.guard.ts
  api/src/lists/lists.controller.ts
  api/src/lists/lists.service.ts
  api/src/users/auth/auth.service.spec.ts
  api/src/users/auth/auth.service.ts
  api/src/users/dtos/user.dto.ts
  api/src/users/guards/comment-auth.guard.ts
  api/src/users/users.controller.spec.ts
  api/src/users/users.controller.ts
  api/test/auth.e2e-spec.ts
Labels: backend, api, hacktoberfest-accepted

#125 Issue-124: Update frontend to match backend schema updates
  web/src/components/List/ListGrid/ListCard.tsx
  web/src/components/List/ListGrid/ListGrid.tsx
  web/src/components/List/MovieListCard/MovieActions.tsx
  web/src/components/List/MovieListCard/MovieListCard.tsx
  web/src/components/List/MovieListGrid/MovieListContainer.tsx
  web/src/components/List/MovieListGrid/MovieListGrid.tsx
  web/src/components/Login/LoginCard.tsx
  web/src/context/lists.context.tsx
  web/src/types.ts
Labels: bug, frontend

#121 Issue-114: Update theme to revise colours and add light theme
  web/public/cinesync-logo-light.svg
  web/public/imdb-logo-disabled.svg
  web/public/imdb-logo.svg
  web/public/logo.png
  web/src/app/dashboard/about/page.tsx
  web/src/app/dashboard/layout.tsx
  web/src/components/Header/AvatarLogo.tsx
  web/src/components/Header/ColorModeSwitch.tsx
  web/src/components/Header/Header.tsx
  web/src/components/List/ListActions.tsx
  web/src/components/List/MovieListCard/MovieActions.tsx
  web/src/components/List/MovieListCard/MovieListCard.tsx
  web/src/components/Login/AuthMain.tsx
  web/src/components/Login/LoginCard.tsx
  web/src/components/Login/SignupCard.tsx
  web/src/components/Login/authMain.module.css
  web/src/components/UserProfile/ProfileBottom.tsx
  web/src/components/UserProfile/ProfileTop.tsx
  web/theme/ThemeRegistry.tsx
  web/theme/theme.ts
Labels: enhancement, frontend

#123 Issue-54: Implement responsive design for all of frontend
  web/src/app/dashboard/(lists)/lists/page.tsx
  web/src/app/dashboard/layout.tsx
  web/src/app/dashboard/list/[slug]/page.tsx
  web/src/app/dashboard/page.tsx
  web/src/components/Header/AvatarLogo.tsx
  web/src/components/Header/Header.tsx
  web/src/components/List/ListDeleteConfirmationModal.tsx
  web/src/components/List/ListGrid/ListCard.tsx
  web/src/components/Login/AuthMain.tsx
  web/src/components/Sidebar/Sidebar.tsx
  web/src/components/UserProfile/ProfileBottom.tsx
Labels: frontend

#126 Issue-73: Add list privacy to frontend
  web/src/components/List/ListActions.tsx
  web/src/components/List/ListGrid/ListCard.tsx
  web/src/components/List/ListGrid/ListGrid.tsx
  web/src/components/List/MovieListGrid/MovieListContainer.tsx
  web/src/components/List/MovieListGrid/MovieListTitle.tsx
  web/src/types.ts
Labels: enhancement, frontend

#120 Issue-41: Mark a movie on a list as watched
  api/prisma/migrations/20231103142249_/migration.sql
  api/prisma/schema.prisma
  api/src/lists/daos/list.dao.ts
  api/src/lists/lists.controller.ts
  api/src/lists/lists.service.ts
  api/src/users/users.controller.spec.ts
Labels: backend

#142 Issue-75: Auto-Close Share Menu after Sharing
  web/src/components/List/ListActions.tsx
  web/src/components/List/ListShareModal.tsx
Labels: bug, frontend

#144 Issue-127: Tweak email service (and add list comment email)
  api/src/email/email.service.ts
  api/src/lists/lists.controller.ts
  api/src/lists/lists.service.ts
Labels: backend

#146 Issue-130: Implement user export
  api/src/users/daos/user.dao.ts
  api/src/users/export/export.controller.spec.ts
  api/src/users/export/export.controller.ts
  api/src/users/export/export.module.ts
  api/src/users/export/export.service.spec.ts
  api/src/users/export/export.service.ts
  api/src/users/users.module.ts
  api/src/users/users.service.ts
Labels: backend

#148 Issue-131: Implement list cloning
  api/src/lists/dtos/clone-list.dto.ts
  api/src/lists/lists.controller.ts
  api/src/lists/lists.service.ts
Labels: backend

#150 Issue-53: Implement a friend management page
  web/src/app/dashboard/friends/page.tsx
  web/src/components/Friends/FriendAction.tsx
  web/src/components/Friends/FriendsAdd.tsx
  web/src/components/Friends/FriendsCard.tsx
  web/src/components/Friends/FriendsContainer.tsx
  web/src/components/Friends/FriendsMain.tsx
  web/src/types.ts
  web/src/utils/cinesync-api/fetch-user.ts
Labels: enhancement, frontend

#154 Issue-57: Implement public list route, add api wide auth
  api/src/app.module.ts
  api/src/lists/daos/list.dao.ts
  api/src/lists/guards/list.guard.ts
  api/src/lists/lists.controller.ts
  api/src/lists/lists.service.ts
  api/src/users/decorators/public.decorator.ts
  api/src/users/guards/jwt-auth.guard.ts
  api/src/users/users.controller.ts
Labels: backend

#156 Various API fixes (see desc)
  api/src/lists/daos/list.dao.ts
  api/src/lists/guards/list-private.guard.ts
  api/src/lists/guards/list.guard.ts
  api/src/lists/guards/share-list.guard.ts
  api/src/lists/lists.controller.ts
  api/src/lists/lists.module.ts
  api/src/lists/lists.service.ts
  api/src/users/auth/passport/jwt.strategy.ts
  api/src/users/avatar/avatar.module.ts
  api/src/users/avatar/avatar.service.spec.ts
  api/src/users/avatar/avatar.service.ts
  api/src/users/daos/user.dao.ts
  api/src/users/export/export.module.ts
  api/src/users/guards/comment-auth.guard.ts
  api/src/users/users.controller.spec.ts
  api/src/users/users.controller.ts
  api/src/users/users.module.ts
  api/src/users/users.service.ts
Labels: backend

#159 Issue-137: add back button to list page
  web/src/components/List/MovieListGrid/MovieListTitle.tsx
Labels: enhancement, frontend

#160 Issue-143: Add list comment support on frontend
  api/src/lists/daos/list.dao.ts
  web/src/components/List/ListGrid/ListCard.tsx
  web/src/components/List/MovieListGrid/MovieListComments/MovieListComment.tsx
  web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentAdd.tsx
  web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentEdit.tsx
  web/src/components/List/MovieListGrid/MovieListComments/MovieListComments.tsx
  web/src/components/List/MovieListGrid/MovieListContainer.tsx
  web/src/context/lists.context.tsx
  web/src/types.ts
  web/src/utils/cinesync-api/fetch-list.ts
  web/src/utils/cinesync-api/fetch-user.ts
  web/src/utils/cinesync-api/fetch.ts
Labels: enhancement, frontend

#153 Issue-77: Show sharee avatars on `List` component
  web/src/components/List/ListActions.tsx
  web/src/components/List/ListGrid/ListCard.tsx
  web/src/components/List/ListGrid/ListCreator.tsx
  web/src/components/List/ListGrid/ListGrid.tsx
  web/src/components/List/ListGrid/ListShareeAvatars.tsx
  web/src/components/List/ListShareModal.tsx
  web/src/types.ts
Labels: enhancement, frontend

#167 Issue-166: Comments with newlines not being rendered on the frontend
  web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentEdit.tsx
Labels: bug, frontend

#169 feat(web): add data export button to user page
  web/src/components/UserProfile/ExportUserData.tsx
  web/src/components/UserProfile/ProfileTop.tsx
  web/src/types.ts
  web/src/utils/cinesync-api/fetch-user.ts
Labels: enhancement, frontend

#165 Issue-163: Add Common Dialog for Deletion
  web/src/components/List/ListActions.tsx
  web/src/components/List/ListDeleteConfirmationModal.tsx
  web/src/components/List/MovieListCard/MovieActions.tsx
  web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentEdit.tsx
  web/src/components/UserProfile/ProfileTop.tsx
  web/src/components/common/DeleteConfirmationDialog/DeleteConfirmationDialog.tsx
Labels: frontend

#170 Issue-151: change avatar callbacks to use utils functions
  web/src/components/Friends/FriendsCard.tsx
  web/src/components/List/ListGrid/ListCreator.tsx
  web/src/components/List/ListGrid/ListShareeAvatars.tsx
  web/src/context/user.context.tsx
Labels: frontend

#171 Issue-136: Disallow sharees (non-creators) from sharing/deleting a movie list
  web/src/components/List/ListActions.tsx
  web/src/components/List/ListGrid/ListCard.tsx
  web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentEdit.tsx
  web/src/components/List/MovieListGrid/MovieListContainer.tsx
  web/src/components/List/MovieListGrid/MovieListTitle.tsx
Labels: bug, enhancement, frontend
